In [2]:
import numpy as np

a=np.arange(15)

a=np.arange(15).reshape(3,5)

In [ ]:
#size of array
a.size

In [4]:
# stacking Array 
a=np.floor(10*np.random.random((2,2)))
b=np.floor(10*np.random.random((2,2)))

In [8]:
x= np.linspace(10,99,100).reshape(10,10).astype(int)
print(x)

[[10 10 11 12 13 14 15 16 17 18]
 [18 19 20 21 22 23 24 25 26 27]
 [27 28 29 30 31 32 33 34 35 36]
 [36 37 38 39 40 41 42 43 44 45]
 [45 46 47 48 49 50 51 52 53 54]
 [54 55 56 57 58 59 60 61 62 63]
 [63 64 65 66 67 68 69 70 71 72]
 [72 73 74 75 76 77 78 79 80 81]
 [81 82 83 84 85 86 87 88 89 90]
 [90 91 92 93 94 95 96 97 98 99]]


In [9]:
print(x[0,0])# 1st element


10


In [11]:
print(x[-1,-1]) #last

99


In [12]:
print(x[5,7]) # 5th & 7th colum

61
